# Generated by Django 2.0 on 2018-11-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoulloapp', '0003_date04_date05_date06_date07'),
    ]

    operations = [
        migrations.CreateModel(
            name='date08',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
        migrations.CreateModel(
            name='date09',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
        migrations.CreateModel(
            name='date10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
        migrations.CreateModel(
            name='date11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
        migrations.CreateModel(
            name='date12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
        migrations.CreateModel(
            name='date13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
    ]
