# Generated by Django 2.0 on 2018-11-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoulloapp', '0004_date08_date09_date10_date11_date12_date13'),
    ]

    operations = [
        migrations.CreateModel(
            name='date14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
        migrations.CreateModel(
            name='date16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
        migrations.CreateModel(
            name='date17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
        migrations.CreateModel(
            name='date18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
        migrations.CreateModel(
            name='date19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
        migrations.CreateModel(
            name='date20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
        migrations.CreateModel(
            name='date21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
        migrations.CreateModel(
            name='date22',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
        migrations.CreateModel(
            name='date23',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
        migrations.CreateModel(
            name='date24',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
        migrations.CreateModel(
            name='date26',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
        migrations.CreateModel(
            name='date28',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
        migrations.CreateModel(
            name='date29',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
        migrations.CreateModel(
            name='date30',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=50)),
                ('first_time_seen', models.CharField(max_length=50)),
                ('last_time_seen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'date01',
                'verbose_name_plural': 'date01',
            },
        ),
    ]
