# Generated by Django 2.1.3 on 2018-11-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seoulloapp', '0005_date14_date16_date17_date18_date19_date20_date21_date22_date23_date24_date26_date28_date29_date30'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='date09',
            new_name='date1',
        ),
        migrations.RenameModel(
            old_name='date06',
            new_name='date2',
        ),
        migrations.RenameModel(
            old_name='date08',
            new_name='date3',
        ),
        migrations.RenameModel(
            old_name='date02',
            new_name='date4',
        ),
        migrations.RenameModel(
            old_name='date04',
            new_name='date5',
        ),
        migrations.RenameModel(
            old_name='date03',
            new_name='date6',
        ),
        migrations.RenameModel(
            old_name='date07',
            new_name='date7',
        ),
        migrations.RenameModel(
            old_name='date05',
            new_name='date8',
        ),
        migrations.RenameModel(
            old_name='date01',
            new_name='date9',
        ),
        migrations.AlterModelOptions(
            name='date1',
            options={'verbose_name': 'date1', 'verbose_name_plural': 'date1'},
        ),
        migrations.AlterModelOptions(
            name='date10',
            options={'verbose_name': 'date10', 'verbose_name_plural': 'date10'},
        ),
        migrations.AlterModelOptions(
            name='date11',
            options={'verbose_name': 'date11', 'verbose_name_plural': 'date11'},
        ),
        migrations.AlterModelOptions(
            name='date12',
            options={'verbose_name': 'date12', 'verbose_name_plural': 'date12'},
        ),
        migrations.AlterModelOptions(
            name='date13',
            options={'verbose_name': 'date13', 'verbose_name_plural': 'date13'},
        ),
        migrations.AlterModelOptions(
            name='date14',
            options={'verbose_name': 'date14', 'verbose_name_plural': 'date14'},
        ),
        migrations.AlterModelOptions(
            name='date16',
            options={'verbose_name': 'date16', 'verbose_name_plural': 'date16'},
        ),
        migrations.AlterModelOptions(
            name='date17',
            options={'verbose_name': 'date17', 'verbose_name_plural': 'date17'},
        ),
        migrations.AlterModelOptions(
            name='date18',
            options={'verbose_name': 'date18', 'verbose_name_plural': 'date18'},
        ),
        migrations.AlterModelOptions(
            name='date19',
            options={'verbose_name': 'date19', 'verbose_name_plural': 'date19'},
        ),
        migrations.AlterModelOptions(
            name='date2',
            options={'verbose_name': 'date2', 'verbose_name_plural': 'date2'},
        ),
        migrations.AlterModelOptions(
            name='date20',
            options={'verbose_name': 'date20', 'verbose_name_plural': 'date20'},
        ),
        migrations.AlterModelOptions(
            name='date21',
            options={'verbose_name': 'date21', 'verbose_name_plural': 'date21'},
        ),
        migrations.AlterModelOptions(
            name='date22',
            options={'verbose_name': 'date22', 'verbose_name_plural': 'date22'},
        ),
        migrations.AlterModelOptions(
            name='date23',
            options={'verbose_name': 'date23', 'verbose_name_plural': 'date23'},
        ),
        migrations.AlterModelOptions(
            name='date24',
            options={'verbose_name': 'date24', 'verbose_name_plural': 'date24'},
        ),
        migrations.AlterModelOptions(
            name='date26',
            options={'verbose_name': 'date26', 'verbose_name_plural': 'date26'},
        ),
        migrations.AlterModelOptions(
            name='date28',
            options={'verbose_name': 'date28', 'verbose_name_plural': 'date28'},
        ),
        migrations.AlterModelOptions(
            name='date29',
            options={'verbose_name': 'date29', 'verbose_name_plural': 'date29'},
        ),
        migrations.AlterModelOptions(
            name='date3',
            options={'verbose_name': 'date3', 'verbose_name_plural': 'date3'},
        ),
        migrations.AlterModelOptions(
            name='date30',
            options={'verbose_name': 'date30', 'verbose_name_plural': 'date30'},
        ),
        migrations.AlterModelOptions(
            name='date4',
            options={'verbose_name': 'date4', 'verbose_name_plural': 'date4'},
        ),
        migrations.AlterModelOptions(
            name='date5',
            options={'verbose_name': 'date5', 'verbose_name_plural': 'date5'},
        ),
        migrations.AlterModelOptions(
            name='date6',
            options={'verbose_name': 'date6', 'verbose_name_plural': 'date6'},
        ),
        migrations.AlterModelOptions(
            name='date7',
            options={'verbose_name': 'date7', 'verbose_name_plural': 'date7'},
        ),
        migrations.AlterModelOptions(
            name='date8',
            options={'verbose_name': 'date8', 'verbose_name_plural': 'date8'},
        ),
        migrations.AlterModelOptions(
            name='date9',
            options={'verbose_name': 'date9', 'verbose_name_plural': 'date9'},
        ),
    ]
